SELECT T1.TABLE_NAME, T1.COLUMN_NAME, 
	T1.CONSTRAINT_NAME AS [ConstraintName1], T1.CONSTRAINT_TYPE AS [ConstraintType1], 
	T2.CONSTRAINT_NAME AS [ConstraintName2], T2.CONSTRAINT_TYPE AS [ConstraintType2] 
FROM
	(
		SELECT TC.CONSTRAINT_NAME, TC.CONSTRAINT_TYPE, TC.TABLE_NAME, CU.COLUMN_NAME
		FROM 
			[RaterooDebug].[INFORMATION_SCHEMA].[TABLE_CONSTRAINTS] AS TC 
			INNER JOIN 
			[RaterooDebug].[INFORMATION_SCHEMA].[CONSTRAINT_COLUMN_USAGE] AS CU
			ON TC.CONSTRAINT_NAME = CU.CONSTRAINT_NAME
	) AS T1
	INNER JOIN
	(
		SELECT TC.CONSTRAINT_NAME, TC.CONSTRAINT_TYPE, TC.TABLE_NAME, CU.COLUMN_NAME
		FROM 
			[RaterooDebug].[INFORMATION_SCHEMA].[TABLE_CONSTRAINTS] AS TC 
			INNER JOIN 
			[RaterooDebug].[INFORMATION_SCHEMA].[CONSTRAINT_COLUMN_USAGE] AS CU
			ON TC.CONSTRAINT_NAME = CU.CONSTRAINT_NAME
	) AS T2
	ON 
		T1.TABLE_NAME = T2.TABLE_NAME AND 
		T1.COLUMN_NAME = T2.COLUMN_NAME AND 
		T1.CONSTRAINT_TYPE <> T2.CONSTRAINT_TYPE