//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.ModelFromDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChoiceGroupFieldDefinition
    {
        public ChoiceGroupFieldDefinition()
        {
            this.ChoiceGroupFieldDefinitions1 = new HashSet<ChoiceGroupFieldDefinition>();
        }
    
        public int ChoiceGroupFieldDefinitionID { get; set; }
        public int ChoiceGroupID { get; set; }
        public int FieldDefinitionID { get; set; }
        public Nullable<int> DependentOnChoiceGroupFieldDefinitionID { get; set; }
        public bool TrackTrustBasedOnChoices { get; set; }
        public byte Status { get; set; }
    
        public virtual ChoiceGroup ChoiceGroup { get; set; }
        public virtual FieldDefinition FieldDefinition { get; set; }
        public virtual ICollection<ChoiceGroupFieldDefinition> ChoiceGroupFieldDefinitions1 { get; set; }
        public virtual ChoiceGroupFieldDefinition ChoiceGroupFieldDefinition1 { get; set; }
    }
}
