//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.ModelFromDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChoiceGroup
    {
        public ChoiceGroup()
        {
            this.ChoiceGroupFieldDefinitions = new HashSet<ChoiceGroupFieldDefinition>();
            this.ChoiceInGroups = new HashSet<ChoiceInGroup>();
            this.ChoiceGroups1 = new HashSet<ChoiceGroup>();
        }
    
        public int ChoiceGroupID { get; set; }
        public int PointsManagerID { get; set; }
        public bool AllowMultipleSelections { get; set; }
        public bool Alphabetize { get; set; }
        public bool InvisibleWhenEmpty { get; set; }
        public bool ShowTagCloud { get; set; }
        public bool PickViaAutoComplete { get; set; }
        public Nullable<int> DependentOnChoiceGroupID { get; set; }
        public bool ShowAllPossibilitiesIfNoDependentChoice { get; set; }
        public bool AlphabetizeWhenShowingAllPossibilities { get; set; }
        public bool AllowAutoAddWhenAddingFields { get; set; }
        public string Name { get; set; }
        public Nullable<int> Creator { get; set; }
        public byte Status { get; set; }
    
        public virtual ICollection<ChoiceGroupFieldDefinition> ChoiceGroupFieldDefinitions { get; set; }
        public virtual ICollection<ChoiceInGroup> ChoiceInGroups { get; set; }
        public virtual ICollection<ChoiceGroup> ChoiceGroups1 { get; set; }
        public virtual ChoiceGroup ChoiceGroup1 { get; set; }
        public virtual PointsManager PointsManager { get; set; }
        public virtual User User { get; set; }
    }
}
