//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.ModelFromDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        public Field()
        {
            this.AddressFields = new HashSet<AddressField>();
            this.ChoiceFields = new HashSet<ChoiceField>();
            this.DateTimeFields = new HashSet<DateTimeField>();
            this.NumberFields = new HashSet<NumberField>();
            this.TextFields = new HashSet<TextField>();
        }
    
        public int FieldID { get; set; }
        public int TblRowID { get; set; }
        public int FieldDefinitionID { get; set; }
        public byte Status { get; set; }
    
        public virtual ICollection<AddressField> AddressFields { get; set; }
        public virtual ICollection<ChoiceField> ChoiceFields { get; set; }
        public virtual ICollection<DateTimeField> DateTimeFields { get; set; }
        public virtual FieldDefinition FieldDefinition { get; set; }
        public virtual ICollection<NumberField> NumberFields { get; set; }
        public virtual ICollection<TextField> TextFields { get; set; }
        public virtual TblRow TblRow { get; set; }
    }
}
