//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.ModelFromDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forum
    {
        public int ForumID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool Premoderated { get; set; }
        public int GroupID { get; set; }
        public bool MembersOnly { get; set; }
        public int OrderByNumber { get; set; }
        public bool RestrictTopicCreation { get; set; }
        public string IconFile { get; set; }
    }
}
