//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.ModelFromDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumUploadedPersonalFile
    {
        public int FileID { get; set; }
        public string FileName { get; set; }
        public int MessageID { get; set; }
        public int UserID { get; set; }
    }
}
