//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.ModelFromDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsertableContent
    {
        public int InsertableContentID { get; set; }
        public string Name { get; set; }
        public Nullable<int> DomainID { get; set; }
        public Nullable<int> PointsManagerID { get; set; }
        public Nullable<int> TblID { get; set; }
        public string Content { get; set; }
        public bool IsTextOnly { get; set; }
        public bool Overridable { get; set; }
        public short Location { get; set; }
        public byte Status { get; set; }
    
        public virtual Domain Domain { get; set; }
        public virtual PointsManager PointsManager { get; set; }
        public virtual Tbl Tbl { get; set; }
    }
}
