//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.ModelFromDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class OverrideCharacteristic
    {
        public int OverrideCharacteristicsID { get; set; }
        public int RatingGroupAttributesID { get; set; }
        public int TblRowID { get; set; }
        public int TblColumnID { get; set; }
        public byte Status { get; set; }
    
        public virtual RatingGroupAttribute RatingGroupAttribute { get; set; }
        public virtual TblColumn TblColumn { get; set; }
        public virtual TblRow TblRow { get; set; }
    }
}
