//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.ModelFromDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointsManager
    {
        public PointsManager()
        {
            this.AdministrationRightsGroups = new HashSet<AdministrationRightsGroup>();
            this.ChangesGroups = new HashSet<ChangesGroup>();
            this.ChoiceGroups = new HashSet<ChoiceGroup>();
            this.InsertableContents = new HashSet<InsertableContent>();
            this.PointsAdjustments = new HashSet<PointsAdjustment>();
            this.PointsTotals = new HashSet<PointsTotal>();
            this.ProposalEvaluationRatingSettings = new HashSet<ProposalEvaluationRatingSetting>();
            this.ProposalSettings = new HashSet<ProposalSetting>();
            this.RatingGroupAttributes = new HashSet<RatingGroupAttribute>();
            this.RewardRatingSettings = new HashSet<RewardRatingSetting>();
            this.Tbls = new HashSet<Tbl>();
            this.UsersAdministrationRightsGroups = new HashSet<UsersAdministrationRightsGroup>();
            this.UsersRights = new HashSet<UsersRight>();
        }
    
        public int PointsManagerID { get; set; }
        public int DomainID { get; set; }
        public Nullable<int> TrustTrackerUnitID { get; set; }
        public decimal CurrentPeriodDollarSubsidy { get; set; }
        public Nullable<System.DateTime> EndOfDollarSubsidyPeriod { get; set; }
        public Nullable<decimal> NextPeriodDollarSubsidy { get; set; }
        public Nullable<int> NextPeriodLength { get; set; }
        public short NumPrizes { get; set; }
        public Nullable<decimal> MinimumPayment { get; set; }
        public decimal TotalUserPoints { get; set; }
        public decimal CurrentUserPoints { get; set; }
        public decimal CurrentUserPendingPoints { get; set; }
        public decimal CurrentUserNotYetPendingPoints { get; set; }
        public decimal CurrentPointsToCount { get; set; }
        public int NumUsersMeetingUltimateStandard { get; set; }
        public int NumUsersMeetingCurrentStandard { get; set; }
        public decimal HighStakesProbability { get; set; }
        public decimal HighStakesSecretMultiplier { get; set; }
        public Nullable<decimal> HighStakesKnownMultiplier { get; set; }
        public bool HighStakesNoviceOn { get; set; }
        public int HighStakesNoviceNumAutomatic { get; set; }
        public int HighStakesNoviceNumOneThird { get; set; }
        public int HighStakesNoviceNumOneTenth { get; set; }
        public decimal DatabaseChangeSelectHighStakesNoviceNumPct { get; set; }
        public int HighStakesNoviceNumActive { get; set; }
        public int HighStakesNoviceTargetNum { get; set; }
        public decimal DollarValuePerPoint { get; set; }
        public decimal DiscountForGuarantees { get; set; }
        public decimal MaximumTotalGuarantees { get; set; }
        public decimal MaximumGuaranteePaymentPerHour { get; set; }
        public decimal TotalUnconditionalGuaranteesEarnedEver { get; set; }
        public decimal TotalConditionalGuaranteesEarnedEver { get; set; }
        public decimal TotalConditionalGuaranteesPending { get; set; }
        public bool AllowApplicationsWhenNoConditionalGuaranteesAvailable { get; set; }
        public bool ConditionalGuaranteesAvailableForNewUsers { get; set; }
        public bool ConditionalGuaranteesAvailableForExistingUsers { get; set; }
        public int ConditionalGuaranteeTimeBlockInHours { get; set; }
        public int ConditionalGuaranteeApplicationsReceived { get; set; }
        public string Name { get; set; }
        public Nullable<int> Creator { get; set; }
        public byte Status { get; set; }
    
        public virtual ICollection<AdministrationRightsGroup> AdministrationRightsGroups { get; set; }
        public virtual ICollection<ChangesGroup> ChangesGroups { get; set; }
        public virtual ICollection<ChoiceGroup> ChoiceGroups { get; set; }
        public virtual Domain Domain { get; set; }
        public virtual ICollection<InsertableContent> InsertableContents { get; set; }
        public virtual ICollection<PointsAdjustment> PointsAdjustments { get; set; }
        public virtual TrustTrackerUnit TrustTrackerUnit { get; set; }
        public virtual ICollection<PointsTotal> PointsTotals { get; set; }
        public virtual ICollection<ProposalEvaluationRatingSetting> ProposalEvaluationRatingSettings { get; set; }
        public virtual ICollection<ProposalSetting> ProposalSettings { get; set; }
        public virtual ICollection<RatingGroupAttribute> RatingGroupAttributes { get; set; }
        public virtual ICollection<RewardRatingSetting> RewardRatingSettings { get; set; }
        public virtual ICollection<Tbl> Tbls { get; set; }
        public virtual ICollection<UsersAdministrationRightsGroup> UsersAdministrationRightsGroups { get; set; }
        public virtual ICollection<UsersRight> UsersRights { get; set; }
    }
}
