//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.ModelFromDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProposalEvaluationRatingSetting
    {
        public int ProposalEvaluationRatingSettingsID { get; set; }
        public Nullable<int> PointsManagerID { get; set; }
        public Nullable<int> UserActionID { get; set; }
        public int RatingGroupAttributesID { get; set; }
        public decimal MinValueToApprove { get; set; }
        public decimal MaxValueToReject { get; set; }
        public int TimeRequiredBeyondThreshold { get; set; }
        public decimal MinProportionOfThisTime { get; set; }
        public int HalfLifeForResolvingAtFinalValue { get; set; }
        public string Name { get; set; }
        public Nullable<int> Creator { get; set; }
        public byte Status { get; set; }
    
        public virtual PointsManager PointsManager { get; set; }
        public virtual RatingGroupAttribute RatingGroupAttribute { get; set; }
        public virtual UserAction UserAction { get; set; }
    }
}
