//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.ModelFromDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingPhaseGroup
    {
        public RatingPhaseGroup()
        {
            this.RatingCharacteristics = new HashSet<RatingCharacteristic>();
            this.RatingGroupPhaseStatus = new HashSet<RatingGroupPhaseStatu>();
            this.RatingPhases = new HashSet<RatingPhas>();
        }
    
        public int RatingPhaseGroupID { get; set; }
        public int NumPhases { get; set; }
        public string Name { get; set; }
        public Nullable<int> Creator { get; set; }
        public byte Status { get; set; }
    
        public virtual ICollection<RatingCharacteristic> RatingCharacteristics { get; set; }
        public virtual ICollection<RatingGroupPhaseStatu> RatingGroupPhaseStatus { get; set; }
        public virtual ICollection<RatingPhas> RatingPhases { get; set; }
        public virtual User User { get; set; }
    }
}
