//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.ModelFromDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingGroupStatusRecord
    {
        public int RatingGroupStatusRecordID { get; set; }
        public int RatingGroupID { get; set; }
        public Nullable<decimal> OldValueOfFirstRating { get; set; }
        public System.DateTime NewValueTime { get; set; }
    
        public virtual RatingGroup RatingGroup { get; set; }
    }
}
