//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.ModelFromDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingPhas
    {
        public RatingPhas()
        {
            this.RatingGroupPhaseStatus = new HashSet<RatingGroupPhaseStatu>();
        }
    
        public int RatingPhaseID { get; set; }
        public int RatingPhaseGroupID { get; set; }
        public int NumberInGroup { get; set; }
        public decimal SubsidyLevel { get; set; }
        public short ScoringRule { get; set; }
        public bool Timed { get; set; }
        public bool BaseTimingOnSpecificTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> RunTime { get; set; }
        public int HalfLifeForResolution { get; set; }
        public bool RepeatIndefinitely { get; set; }
        public Nullable<int> RepeatNTimes { get; set; }
        public byte Status { get; set; }
    
        public virtual ICollection<RatingGroupPhaseStatu> RatingGroupPhaseStatus { get; set; }
        public virtual RatingPhaseGroup RatingPhaseGroup { get; set; }
    }
}
