//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.ModelFromDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingGroup
    {
        public RatingGroup()
        {
            this.RatingGroupPhaseStatus = new HashSet<RatingGroupPhaseStatu>();
            this.RatingGroupResolutions = new HashSet<RatingGroupResolution>();
            this.RatingGroupStatusRecords = new HashSet<RatingGroupStatusRecord>();
            this.UserRatingsToAdds = new HashSet<UserRatingsToAdd>();
            this.VolatilityTrackers = new HashSet<VolatilityTracker>();
            this.Ratings = new HashSet<Rating>();
            this.Ratings1 = new HashSet<Rating>();
            this.Ratings2 = new HashSet<Rating>();
            this.UserRatingGroups = new HashSet<UserRatingGroup>();
        }
    
        public int RatingGroupID { get; set; }
        public int RatingGroupAttributesID { get; set; }
        public int TblRowID { get; set; }
        public int TblColumnID { get; set; }
        public Nullable<decimal> CurrentValueOfFirstRating { get; set; }
        public bool ValueRecentlyChanged { get; set; }
        public Nullable<System.DateTime> ResolutionTime { get; set; }
        public byte TypeOfRatingGroup { get; set; }
        public byte Status { get; set; }
        public bool HighStakesKnown { get; set; }
    
        public virtual RatingGroupAttribute RatingGroupAttribute { get; set; }
        public virtual ICollection<RatingGroupPhaseStatu> RatingGroupPhaseStatus { get; set; }
        public virtual ICollection<RatingGroupResolution> RatingGroupResolutions { get; set; }
        public virtual ICollection<RatingGroupStatusRecord> RatingGroupStatusRecords { get; set; }
        public virtual ICollection<UserRatingsToAdd> UserRatingsToAdds { get; set; }
        public virtual ICollection<VolatilityTracker> VolatilityTrackers { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<Rating> Ratings1 { get; set; }
        public virtual ICollection<Rating> Ratings2 { get; set; }
        public virtual ICollection<UserRatingGroup> UserRatingGroups { get; set; }
        public virtual TblColumn TblColumn { get; set; }
        public virtual TblRow TblRow { get; set; }
    }
}
