//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.ModelFromDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingCondition
    {
        public RatingCondition()
        {
            this.RatingGroupAttributes = new HashSet<RatingGroupAttribute>();
        }
    
        public int RatingConditionID { get; set; }
        public Nullable<int> ConditionRatingID { get; set; }
        public Nullable<decimal> GreaterThan { get; set; }
        public Nullable<decimal> LessThan { get; set; }
        public byte Status { get; set; }
    
        public virtual Rating Rating { get; set; }
        public virtual ICollection<RatingGroupAttribute> RatingGroupAttributes { get; set; }
    }
}
