//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.ModelFromDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RewardPendingPointsTracker
    {
        public RewardPendingPointsTracker()
        {
            this.UserRatings = new HashSet<UserRating>();
        }
    
        public int RewardPendingPointsTrackerID { get; set; }
        public Nullable<decimal> PendingRating { get; set; }
        public Nullable<System.DateTime> TimeOfPendingRating { get; set; }
        public int RewardTblRowID { get; set; }
        public int UserID { get; set; }
    
        public virtual User User { get; set; }
        public virtual TblRow TblRow { get; set; }
        public virtual ICollection<UserRating> UserRatings { get; set; }
    }
}
