//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.ModelFromDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleStatu
    {
        public int RoleStatusID { get; set; }
        public string RoleID { get; set; }
        public Nullable<System.DateTime> LastCheckIn { get; set; }
        public bool IsWorkerRole { get; set; }
        public bool IsBackgroundProcessing { get; set; }
    }
}
