//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.ModelFromDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchWordTblRowName
    {
        public int SearchWordTblRowNameID { get; set; }
        public int TblRowID { get; set; }
        public int SearchWordID { get; set; }
    
        public virtual SearchWord SearchWord { get; set; }
        public virtual TblRow TblRow { get; set; }
    }
}
