//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.ModelFromDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubsidyDensityRangeGroup
    {
        public SubsidyDensityRangeGroup()
        {
            this.RatingCharacteristics = new HashSet<RatingCharacteristic>();
            this.SubsidyDensityRanges = new HashSet<SubsidyDensityRange>();
        }
    
        public int SubsidyDensityRangeGroupID { get; set; }
        public Nullable<decimal> UseLogarithmBase { get; set; }
        public decimal CumDensityTotal { get; set; }
        public string Name { get; set; }
        public Nullable<int> Creator { get; set; }
        public byte Status { get; set; }
    
        public virtual ICollection<RatingCharacteristic> RatingCharacteristics { get; set; }
        public virtual ICollection<SubsidyDensityRange> SubsidyDensityRanges { get; set; }
        public virtual User User { get; set; }
    }
}
