//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.ModelFromDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl
    {
        public Tbl()
        {
            this.ChangesGroups = new HashSet<ChangesGroup>();
            this.FieldDefinitions = new HashSet<FieldDefinition>();
            this.HierarchyItems = new HashSet<HierarchyItem>();
            this.InsertableContents = new HashSet<InsertableContent>();
            this.ProposalSettings = new HashSet<ProposalSetting>();
            this.TblRows = new HashSet<TblRow>();
            this.TrustTrackerForChoiceInGroups = new HashSet<TrustTrackerForChoiceInGroup>();
            this.TblTabs = new HashSet<TblTab>();
        }
    
        public int TblID { get; set; }
        public int PointsManagerID { get; set; }
        public Nullable<int> DefaultRatingGroupAttributesID { get; set; }
        public string TblTabWord { get; set; }
        public string Name { get; set; }
        public string TypeOfTblRow { get; set; }
        public Nullable<int> TblDimensionsID { get; set; }
        public Nullable<int> Creator { get; set; }
        public byte Status { get; set; }
        public bool AllowOverrideOfRatingGroupCharacterstics { get; set; }
        public bool AllowUsersToAddComments { get; set; }
        public bool LimitCommentsToUsersWhoCanMakeUserRatings { get; set; }
        public bool OneRatingPerRatingGroup { get; set; }
        public string TblRowAdditionCriteria { get; set; }
        public string SuppStylesHeader { get; set; }
        public string SuppStylesMain { get; set; }
        public string WidthStyleEntityCol { get; set; }
        public string WidthStyleNumCol { get; set; }
        public byte FastTableSyncStatus { get; set; }
        public int NumTblRowsActive { get; set; }
        public int NumTblRowsDeleted { get; set; }
    
        public virtual ICollection<ChangesGroup> ChangesGroups { get; set; }
        public virtual ICollection<FieldDefinition> FieldDefinitions { get; set; }
        public virtual ICollection<HierarchyItem> HierarchyItems { get; set; }
        public virtual ICollection<InsertableContent> InsertableContents { get; set; }
        public virtual PointsManager PointsManager { get; set; }
        public virtual ICollection<ProposalSetting> ProposalSettings { get; set; }
        public virtual TblDimension TblDimension { get; set; }
        public virtual ICollection<TblRow> TblRows { get; set; }
        public virtual ICollection<TrustTrackerForChoiceInGroup> TrustTrackerForChoiceInGroups { get; set; }
        public virtual ICollection<TblTab> TblTabs { get; set; }
        public virtual User User { get; set; }
    }
}
