//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.ModelFromDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblColumnFormatting
    {
        public int TblColumnFormattingID { get; set; }
        public int TblColumnID { get; set; }
        public string Prefix { get; set; }
        public string Suffix { get; set; }
        public bool OmitLeadingZero { get; set; }
        public Nullable<decimal> ExtraDecimalPlaceAbove { get; set; }
        public Nullable<decimal> ExtraDecimalPlace2Above { get; set; }
        public Nullable<decimal> ExtraDecimalPlace3Above { get; set; }
        public string SuppStylesHeader { get; set; }
        public string SuppStylesMain { get; set; }
        public byte Status { get; set; }
    
        public virtual TblColumn TblColumn { get; set; }
    }
}
