//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.ModelFromDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDimension
    {
        public TblDimension()
        {
            this.Domains = new HashSet<Domain>();
            this.Tbls = new HashSet<Tbl>();
        }
    
        public int TblDimensionsID { get; set; }
        public int MaxWidthOfImageInRowHeaderCell { get; set; }
        public int MaxHeightOfImageInRowHeaderCell { get; set; }
        public int MaxWidthOfImageInTblRowPopUpWindow { get; set; }
        public int MaxHeightOfImageInTblRowPopUpWindow { get; set; }
        public int WidthOfTblRowPopUpWindow { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual ICollection<Domain> Domains { get; set; }
        public virtual ICollection<Tbl> Tbls { get; set; }
    }
}
