//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.ModelFromDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrustTrackerUnit
    {
        public TrustTrackerUnit()
        {
            this.PointsManagers = new HashSet<PointsManager>();
            this.TblColumns = new HashSet<TblColumn>();
            this.TrustTrackers = new HashSet<TrustTracker>();
            this.UserInteractions = new HashSet<UserInteraction>();
            this.UserRatings = new HashSet<UserRating>();
        }
    
        public int TrustTrackerUnitID { get; set; }
        public short SkepticalTrustThreshhold { get; set; }
        public short LastSkepticalTrustThreshhold { get; set; }
        public int MinUpdateIntervalSeconds { get; set; }
        public int MaxUpdateIntervalSeconds { get; set; }
        public decimal ExtendIntervalWhenChangeIsLessThanThis { get; set; }
        public decimal ExtendIntervalMultiplier { get; set; }
    
        public virtual ICollection<PointsManager> PointsManagers { get; set; }
        public virtual ICollection<TblColumn> TblColumns { get; set; }
        public virtual ICollection<TrustTracker> TrustTrackers { get; set; }
        public virtual ICollection<UserInteraction> UserInteractions { get; set; }
        public virtual ICollection<UserRating> UserRatings { get; set; }
    }
}
