//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.ModelFromDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniquenessLockReference
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> UniquenessLockID { get; set; }
    
        public virtual UniquenessLock UniquenessLock { get; set; }
    }
}
