//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.ModelFromDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInteractionStat
    {
        public int UserInteractionStatID { get; set; }
        public int UserInteractionID { get; set; }
        public int TrustTrackerStatID { get; set; }
        public short StatNum { get; set; }
        public double SumAdjustPctTimesWeight { get; set; }
        public double SumWeights { get; set; }
        public double AvgAdjustmentPctWeighted { get; set; }
    
        public virtual TrustTrackerStat TrustTrackerStat { get; set; }
        public virtual UserInteraction UserInteraction { get; set; }
    }
}
