//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.ModelFromDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VolatilityTblRowTracker
    {
        public VolatilityTblRowTracker()
        {
            this.VolatilityTrackers = new HashSet<VolatilityTracker>();
        }
    
        public int VolatilityTblRowTrackerID { get; set; }
        public int TblRowID { get; set; }
        public byte DurationType { get; set; }
        public decimal TotalMovement { get; set; }
        public decimal DistanceFromStart { get; set; }
        public decimal Pushback { get; set; }
        public decimal PushbackProportion { get; set; }
    
        public virtual TblRow TblRow { get; set; }
        public virtual ICollection<VolatilityTracker> VolatilityTrackers { get; set; }
    }
}
