//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangesStatusOfObject
    {
        public int ChangesStatusOfObjectID { get; set; }
        public int ChangesGroupID { get; set; }
        public byte ObjectType { get; set; }
        public bool AddObject { get; set; }
        public bool DeleteObject { get; set; }
        public bool ReplaceObject { get; set; }
        public bool ChangeName { get; set; }
        public bool ChangeOther { get; set; }
        public bool ChangeSetting1 { get; set; }
        public bool ChangeSetting2 { get; set; }
        public bool MayAffectRunningRating { get; set; }
        public string NewName { get; set; }
        public Nullable<int> NewObject { get; set; }
        public Nullable<int> ExistingObject { get; set; }
        public Nullable<bool> NewValueBoolean { get; set; }
        public Nullable<int> NewValueInteger { get; set; }
        public Nullable<decimal> NewValueDecimal { get; set; }
        public string NewValueText { get; set; }
        public Nullable<System.DateTime> NewValueDateTime { get; set; }
        public string ChangeDescription { get; set; }
    
        public virtual ChangesGroup ChangesGroup { get; set; }
    }
}
