//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangesGroup
    {
        public ChangesGroup()
        {
            this.ChangesStatusOfObjects = new HashSet<ChangesStatusOfObject>();
        }
    
        public int ChangesGroupID { get; set; }
        public Nullable<int> PointsManagerID { get; set; }
        public Nullable<int> TblID { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<int> MakeChangeRatingID { get; set; }
        public Nullable<int> RewardRatingID { get; set; }
        public byte StatusOfChanges { get; set; }
        public Nullable<System.DateTime> ScheduleApprovalOrRejection { get; set; }
        public Nullable<System.DateTime> ScheduleImplementation { get; set; }
    
        public virtual ICollection<ChangesStatusOfObject> ChangesStatusOfObjects { get; set; }
        public virtual Rating Rating { get; set; }
        public virtual PointsManager PointsManager { get; set; }
        public virtual Tbl Tbl { get; set; }
        public virtual User User { get; set; }
    }
}
