//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChoiceInField
    {
        public int ChoiceInFieldID { get; set; }
        public int ChoiceFieldID { get; set; }
        public int ChoiceInGroupID { get; set; }
        public byte Status { get; set; }
    
        public virtual ChoiceField ChoiceField { get; set; }
        public virtual ChoiceInGroup ChoiceInGroup { get; set; }
    }
}
