//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChoiceInGroup
    {
        public ChoiceInGroup()
        {
            this.ChoiceInFields = new HashSet<ChoiceInField>();
            this.ChoiceInGroups1 = new HashSet<ChoiceInGroup>();
            this.SearchWordChoices = new HashSet<SearchWordChoice>();
            this.TrustTrackerForChoiceInGroups = new HashSet<TrustTrackerForChoiceInGroup>();
        }
    
        public int ChoiceInGroupID { get; set; }
        public int ChoiceGroupID { get; set; }
        public int ChoiceNum { get; set; }
        public string ChoiceText { get; set; }
        public Nullable<int> ActiveOnDeterminingGroupChoiceInGroupID { get; set; }
        public byte Status { get; set; }
    
        public virtual ChoiceGroup ChoiceGroup { get; set; }
        public virtual ICollection<ChoiceInField> ChoiceInFields { get; set; }
        public virtual ICollection<ChoiceInGroup> ChoiceInGroups1 { get; set; }
        public virtual ChoiceInGroup ChoiceInGroup1 { get; set; }
        public virtual ICollection<SearchWordChoice> SearchWordChoices { get; set; }
        public virtual ICollection<TrustTrackerForChoiceInGroup> TrustTrackerForChoiceInGroups { get; set; }
    }
}
