//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentsID { get; set; }
        public int TblRowID { get; set; }
        public int UserID { get; set; }
        public string CommentTitle { get; set; }
        public string CommentText { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<System.DateTime> LastDeletedDate { get; set; }
        public byte Status { get; set; }
    
        public virtual TblRow TblRow { get; set; }
        public virtual User User { get; set; }
    }
}
