//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domain
    {
        public Domain()
        {
            this.InsertableContents = new HashSet<InsertableContent>();
            this.PointsManagers = new HashSet<PointsManager>();
        }
    
        public int DomainID { get; set; }
        public bool ActiveRatingWebsite { get; set; }
        public string Name { get; set; }
        public Nullable<int> TblDimensionsID { get; set; }
        public Nullable<int> Creator { get; set; }
        public byte Status { get; set; }
    
        public virtual ICollection<InsertableContent> InsertableContents { get; set; }
        public virtual ICollection<PointsManager> PointsManagers { get; set; }
        public virtual TblDimension TblDimension { get; set; }
    }
}
