//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumberFieldDefinition
    {
        public int NumberFieldDefinitionID { get; set; }
        public int FieldDefinitionID { get; set; }
        public Nullable<decimal> Minimum { get; set; }
        public Nullable<decimal> Maximum { get; set; }
        public byte DecimalPlaces { get; set; }
        public byte Status { get; set; }
    
        public virtual FieldDefinition FieldDefinition { get; set; }
    }
}
