//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointsTotal
    {
        public int PointsTotalID { get; set; }
        public int UserID { get; set; }
        public int PointsManagerID { get; set; }
        public decimal CurrentPoints { get; set; }
        public decimal TotalPoints { get; set; }
        public decimal PotentialMaxLossOnNotYetPending { get; set; }
        public decimal PendingPoints { get; set; }
        public decimal NotYetPendingPoints { get; set; }
        public decimal TrustPoints { get; set; }
        public decimal TrustPointsRatio { get; set; }
        public int NumPendingOrFinalizedRatings { get; set; }
        public decimal PointsPerRating { get; set; }
        public Nullable<System.DateTime> FirstUserRating { get; set; }
        public Nullable<System.DateTime> LastCheckIn { get; set; }
        public Nullable<System.DateTime> CurrentCheckInPeriodStart { get; set; }
        public decimal TotalTimeThisCheckInPeriod { get; set; }
        public decimal TotalTimeThisRewardPeriod { get; set; }
        public decimal TotalTimeEver { get; set; }
        public Nullable<decimal> PointsPerHour { get; set; }
        public Nullable<decimal> ProjectedPointsPerHour { get; set; }
        public decimal GuaranteedPaymentsEarnedThisRewardPeriod { get; set; }
        public string PendingConditionalGuaranteeApplication { get; set; }
        public Nullable<decimal> PendingConditionalGuaranteePayment { get; set; }
        public Nullable<decimal> PendingConditionalGuaranteeTotalHoursAtStart { get; set; }
        public Nullable<decimal> PendingConditionalGuaranteeTotalHoursNeeded { get; set; }
        public Nullable<decimal> PendingConditionalGuaranteePaymentAlreadyMade { get; set; }
        public Nullable<System.DateTime> RequestConditionalGuaranteeWhenAvailableTimeRequestMade { get; set; }
        public decimal TotalPointsOrPendingPointsLongTermUnweighted { get; set; }
        public decimal PointsPerRatingLongTerm { get; set; }
        public float PointsPumpingProportionAvg_Numer { get; set; }
        public float PointsPumpingProportionAvg_Denom { get; set; }
        public float PointsPumpingProportionAvg { get; set; }
        public int NumUserRatings { get; set; }
    
        public virtual PointsManager PointsManager { get; set; }
        public virtual User User { get; set; }
    }
}
