//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointsAdjustment
    {
        public int PointsAdjustmentID { get; set; }
        public int UserID { get; set; }
        public int PointsManagerID { get; set; }
        public int Reason { get; set; }
        public decimal TotalAdjustment { get; set; }
        public decimal CurrentAdjustment { get; set; }
        public Nullable<decimal> CashValue { get; set; }
        public System.DateTime WhenMade { get; set; }
        public byte Status { get; set; }
    
        public virtual PointsManager PointsManager { get; set; }
        public virtual User User { get; set; }
    }
}
