//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingGroupPhaseStatu
    {
        public RatingGroupPhaseStatu()
        {
            this.RatingPhaseStatus = new HashSet<RatingPhaseStatu>();
            this.UserRatingGroups = new HashSet<UserRatingGroup>();
            this.SubsidyAdjustments = new HashSet<SubsidyAdjustment>();
        }
    
        public int RatingGroupPhaseStatusID { get; set; }
        public int RatingPhaseGroupID { get; set; }
        public int RatingPhaseID { get; set; }
        public int RatingGroupID { get; set; }
        public int RoundNum { get; set; }
        public int RoundNumThisPhase { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EarliestCompleteTime { get; set; }
        public System.DateTime ActualCompleteTime { get; set; }
        public System.DateTime ShortTermResolveTime { get; set; }
        public bool HighStakesSecret { get; set; }
        public bool HighStakesKnown { get; set; }
        public bool HighStakesReflected { get; set; }
        public bool HighStakesNoviceUser { get; set; }
        public Nullable<System.DateTime> HighStakesBecomeKnown { get; set; }
        public Nullable<System.DateTime> HighStakesNoviceUserAfter { get; set; }
    
        public virtual RatingGroup RatingGroup { get; set; }
        public virtual ICollection<RatingPhaseStatu> RatingPhaseStatus { get; set; }
        public virtual ICollection<UserRatingGroup> UserRatingGroups { get; set; }
        public virtual ICollection<SubsidyAdjustment> SubsidyAdjustments { get; set; }
        public virtual RatingPhas RatingPhas { get; set; }
        public virtual RatingPhaseGroup RatingPhaseGroup { get; set; }
    }
}
