//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingPlan
    {
        public int RatingPlansID { get; set; }
        public int RatingGroupAttributesID { get; set; }
        public int NumInGroup { get; set; }
        public Nullable<int> OwnedRatingGroupAttributesID { get; set; }
        public Nullable<decimal> DefaultUserRating { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Creator { get; set; }
        public byte Status { get; set; }
    
        public virtual RatingGroupAttribute RatingGroupAttribute { get; set; }
        public virtual RatingGroupAttribute RatingGroupAttribute1 { get; set; }
        public virtual User User { get; set; }
    }
}
