//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingGroupResolution
    {
        public int RatingGroupResolutionID { get; set; }
        public int RatingGroupID { get; set; }
        public bool CancelPreviousResolutions { get; set; }
        public bool ResolveByUnwinding { get; set; }
        public System.DateTime EffectiveTime { get; set; }
        public Nullable<System.DateTime> ExecutionTime { get; set; }
        public Nullable<int> Creator { get; set; }
        public byte Status { get; set; }
    
        public virtual RatingGroup RatingGroup { get; set; }
        public virtual User User { get; set; }
    }
}
