//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingPhaseStatu
    {
        public RatingPhaseStatu()
        {
            this.UserRatings = new HashSet<UserRating>();
        }
    
        public int RatingPhaseStatusID { get; set; }
        public int RatingGroupPhaseStatusID { get; set; }
        public int RatingID { get; set; }
        public Nullable<decimal> ShortTermResolutionValue { get; set; }
        public int NumUserRatingsMadeDuringPhase { get; set; }
        public bool TriggerUserRatingsUpdate { get; set; }
    
        public virtual RatingGroupPhaseStatu RatingGroupPhaseStatu { get; set; }
        public virtual Rating Rating { get; set; }
        public virtual ICollection<UserRating> UserRatings { get; set; }
    }
}
