//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public Rating()
        {
            this.ChangesGroups = new HashSet<ChangesGroup>();
            this.RatingConditions = new HashSet<RatingCondition>();
            this.RatingPhaseStatus = new HashSet<RatingPhaseStatu>();
            this.UserRatings = new HashSet<UserRating>();
        }
    
        public int RatingID { get; set; }
        public int RatingGroupID { get; set; }
        public int RatingCharacteristicsID { get; set; }
        public Nullable<int> OwnedRatingGroupID { get; set; }
        public int TopmostRatingGroupID { get; set; }
        public Nullable<int> MostRecentUserRatingID { get; set; }
        public int NumInGroup { get; set; }
        public int TotalUserRatings { get; set; }
        public string Name { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<decimal> CurrentValue { get; set; }
        public Nullable<decimal> LastTrustedValue { get; set; }
        public System.DateTime LastModifiedResolutionTimeOrCurrentValue { get; set; }
        public Nullable<System.DateTime> ReviewRecentUserRatingsAfter { get; set; }
    
        public virtual ICollection<ChangesGroup> ChangesGroups { get; set; }
        public virtual RatingCharacteristic RatingCharacteristic { get; set; }
        public virtual ICollection<RatingCondition> RatingConditions { get; set; }
        public virtual RatingGroup RatingGroup { get; set; }
        public virtual RatingGroup RatingGroup1 { get; set; }
        public virtual RatingGroup RatingGroup2 { get; set; }
        public virtual ICollection<RatingPhaseStatu> RatingPhaseStatus { get; set; }
        public virtual UserRating UserRating { get; set; }
        public virtual ICollection<UserRating> UserRatings { get; set; }
        public virtual User User { get; set; }
    }
}
