//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class RewardRatingSetting
    {
        public int RewardRatingSettingsID { get; set; }
        public Nullable<int> PointsManagerID { get; set; }
        public Nullable<int> UserActionID { get; set; }
        public int RatingGroupAttributesID { get; set; }
        public decimal ProbOfRewardEvaluation { get; set; }
        public Nullable<decimal> Multiplier { get; set; }
        public string Name { get; set; }
        public Nullable<int> Creator { get; set; }
        public byte Status { get; set; }
    
        public virtual PointsManager PointsManager { get; set; }
        public virtual RatingGroupAttribute RatingGroupAttribute { get; set; }
        public virtual UserAction UserAction { get; set; }
    }
}
