//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchWordChoice
    {
        public int SearchWordChoiceID { get; set; }
        public int ChoiceInGroupID { get; set; }
        public int SearchWordID { get; set; }
    
        public virtual ChoiceInGroup ChoiceInGroup { get; set; }
        public virtual SearchWord SearchWord { get; set; }
    }
}
