//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubsidyAdjustment
    {
        public int SubsidyAdjustmentID { get; set; }
        public int RatingGroupPhaseStatusID { get; set; }
        public decimal SubsidyAdjustmentFactor { get; set; }
        public System.DateTime EffectiveTime { get; set; }
        public Nullable<System.DateTime> EndingTime { get; set; }
        public Nullable<int> EndingTimeHalfLife { get; set; }
        public byte Status { get; set; }
    
        public virtual RatingGroupPhaseStatu RatingGroupPhaseStatu { get; set; }
    }
}
