//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRowFieldDisplay
    {
        public TblRowFieldDisplay()
        {
            this.TblRows = new HashSet<TblRow>();
        }
    
        public int TblRowFieldDisplayID { get; set; }
        public string Row { get; set; }
        public string PopUp { get; set; }
        public string TblRowPage { get; set; }
        public bool ResetNeeded { get; set; }
    
        public virtual ICollection<TblRow> TblRows { get; set; }
    }
}
