//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTab
    {
        public TblTab()
        {
            this.TblColumns = new HashSet<TblColumn>();
        }
    
        public int TblTabID { get; set; }
        public int TblID { get; set; }
        public int NumInTbl { get; set; }
        public string Name { get; set; }
        public Nullable<int> DefaultSortTblColumnID { get; set; }
        public byte Status { get; set; }
    
        public virtual ICollection<TblColumn> TblColumns { get; set; }
        public virtual Tbl Tbl { get; set; }
    }
}
