//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrustTracker
    {
        public TrustTracker()
        {
            this.TrustTrackerStats = new HashSet<TrustTrackerStat>();
        }
    
        public int TrustTrackerID { get; set; }
        public int TrustTrackerUnitID { get; set; }
        public int UserID { get; set; }
        public double OverallTrustLevel { get; set; }
        public double OverallTrustLevelAtLastReview { get; set; }
        public double DeltaOverallTrustLevel { get; set; }
        public double SkepticalTrustLevel { get; set; }
        public double SumUserInteractionWeights { get; set; }
        public double EgalitarianTrustLevel { get; set; }
        public double Egalitarian_Num { get; set; }
        public double Egalitarian_Denom { get; set; }
        public Nullable<double> EgalitarianTrustLevelOverride { get; set; }
        public bool MustUpdateUserInteractionEgalitarianTrustLevel { get; set; }
    
        public virtual TrustTrackerUnit TrustTrackerUnit { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<TrustTrackerStat> TrustTrackerStats { get; set; }
    }
}
