//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrustTrackerForChoiceInGroup
    {
        public TrustTrackerForChoiceInGroup()
        {
            this.TrustTrackerForChoiceInGroupsUserRatingLinks = new HashSet<TrustTrackerForChoiceInGroupsUserRatingLink>();
        }
    
        public int TrustTrackerForChoiceInGroupID { get; set; }
        public int UserID { get; set; }
        public int ChoiceInGroupID { get; set; }
        public int TblID { get; set; }
        public float SumAdjustmentPctTimesRatingMagnitude { get; set; }
        public float SumRatingMagnitudes { get; set; }
        public float TrustLevelForChoice { get; set; }
    
        public virtual ChoiceInGroup ChoiceInGroup { get; set; }
        public virtual Tbl Tbl { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<TrustTrackerForChoiceInGroupsUserRatingLink> TrustTrackerForChoiceInGroupsUserRatingLinks { get; set; }
    }
}
