//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrustTrackerForChoiceInGroupsUserRatingLink
    {
        public int TrustTrackerForChoiceInGroupsUserRatingLinkID { get; set; }
        public int UserRatingID { get; set; }
        public int TrustTrackerForChoiceInGroupID { get; set; }
    
        public virtual TrustTrackerForChoiceInGroup TrustTrackerForChoiceInGroup { get; set; }
        public virtual UserRating UserRating { get; set; }
    }
}
