//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ChangesGroups = new HashSet<ChangesGroup>();
            this.ChoiceGroups = new HashSet<ChoiceGroup>();
            this.Comments = new HashSet<Comment>();
            this.PointsAdjustments = new HashSet<PointsAdjustment>();
            this.PointsTotals = new HashSet<PointsTotal>();
            this.RatingCharacteristics = new HashSet<RatingCharacteristic>();
            this.RatingGroupResolutions = new HashSet<RatingGroupResolution>();
            this.RatingPhaseGroups = new HashSet<RatingPhaseGroup>();
            this.RatingPlans = new HashSet<RatingPlan>();
            this.Ratings = new HashSet<Rating>();
            this.RewardPendingPointsTrackers = new HashSet<RewardPendingPointsTracker>();
            this.SubsidyDensityRangeGroups = new HashSet<SubsidyDensityRangeGroup>();
            this.Tbls = new HashSet<Tbl>();
            this.TrustTrackerForChoiceInGroups = new HashSet<TrustTrackerForChoiceInGroup>();
            this.TrustTrackers = new HashSet<TrustTracker>();
            this.UserCheckIns = new HashSet<UserCheckIn>();
            this.UserInfoes = new HashSet<UserInfo>();
            this.UserInteractions = new HashSet<UserInteraction>();
            this.UserInteractions1 = new HashSet<UserInteraction>();
            this.UserRatings = new HashSet<UserRating>();
            this.UserRatingsToAdds = new HashSet<UserRatingsToAdd>();
            this.UsersAdministrationRightsGroups = new HashSet<UsersAdministrationRightsGroup>();
            this.UsersRights = new HashSet<UsersRight>();
        }
    
        public int UserID { get; set; }
        public string Username { get; set; }
        public bool SuperUser { get; set; }
        public decimal TrustPointsRatioTotals { get; set; }
        public byte Status { get; set; }
    
        public virtual ICollection<ChangesGroup> ChangesGroups { get; set; }
        public virtual ICollection<ChoiceGroup> ChoiceGroups { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<PointsAdjustment> PointsAdjustments { get; set; }
        public virtual ICollection<PointsTotal> PointsTotals { get; set; }
        public virtual ICollection<RatingCharacteristic> RatingCharacteristics { get; set; }
        public virtual ICollection<RatingGroupResolution> RatingGroupResolutions { get; set; }
        public virtual ICollection<RatingPhaseGroup> RatingPhaseGroups { get; set; }
        public virtual ICollection<RatingPlan> RatingPlans { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<RewardPendingPointsTracker> RewardPendingPointsTrackers { get; set; }
        public virtual ICollection<SubsidyDensityRangeGroup> SubsidyDensityRangeGroups { get; set; }
        public virtual ICollection<Tbl> Tbls { get; set; }
        public virtual ICollection<TrustTrackerForChoiceInGroup> TrustTrackerForChoiceInGroups { get; set; }
        public virtual ICollection<TrustTracker> TrustTrackers { get; set; }
        public virtual ICollection<UserCheckIn> UserCheckIns { get; set; }
        public virtual ICollection<UserInfo> UserInfoes { get; set; }
        public virtual ICollection<UserInteraction> UserInteractions { get; set; }
        public virtual ICollection<UserInteraction> UserInteractions1 { get; set; }
        public virtual ICollection<UserRating> UserRatings { get; set; }
        public virtual ICollection<UserRatingsToAdd> UserRatingsToAdds { get; set; }
        public virtual ICollection<UsersAdministrationRightsGroup> UsersAdministrationRightsGroups { get; set; }
        public virtual ICollection<UsersRight> UsersRights { get; set; }
    }
}
