//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAction
    {
        public UserAction()
        {
            this.AdministrationRights = new HashSet<AdministrationRight>();
            this.ProposalEvaluationRatingSettings = new HashSet<ProposalEvaluationRatingSetting>();
            this.RewardRatingSettings = new HashSet<RewardRatingSetting>();
        }
    
        public int UserActionID { get; set; }
        public string Text { get; set; }
        public bool SuperUser { get; set; }
    
        public virtual ICollection<AdministrationRight> AdministrationRights { get; set; }
        public virtual ICollection<ProposalEvaluationRatingSetting> ProposalEvaluationRatingSettings { get; set; }
        public virtual ICollection<RewardRatingSetting> RewardRatingSettings { get; set; }
    }
}
