//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersAdministrationRightsGroup
    {
        public int UsersAdministrationRightsGroupID { get; set; }
        public Nullable<int> UserID { get; set; }
        public int PointsManagerID { get; set; }
        public int AdministrationRightsGroupID { get; set; }
        public byte Status { get; set; }
    
        public virtual AdministrationRightsGroup AdministrationRightsGroup { get; set; }
        public virtual PointsManager PointsManager { get; set; }
        public virtual User User { get; set; }
    }
}
