//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRatingGroup
    {
        public UserRatingGroup()
        {
            this.UserRatings = new HashSet<UserRating>();
        }
    
        public int UserRatingGroupID { get; set; }
        public int RatingGroupID { get; set; }
        public int RatingGroupPhaseStatusID { get; set; }
        public System.DateTime WhenMade { get; set; }
    
        public virtual RatingGroupPhaseStatu RatingGroupPhaseStatu { get; set; }
        public virtual RatingGroup RatingGroup { get; set; }
        public virtual ICollection<UserRating> UserRatings { get; set; }
    }
}
