//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class VolatilityTracker
    {
        public int VolatilityTrackerID { get; set; }
        public int RatingGroupID { get; set; }
        public int VolatilityTblRowTrackerID { get; set; }
        public byte DurationType { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public decimal TotalMovement { get; set; }
        public decimal DistanceFromStart { get; set; }
        public decimal Pushback { get; set; }
        public decimal PushbackProportion { get; set; }
    
        public virtual RatingGroup RatingGroup { get; set; }
        public virtual VolatilityTblRowTracker VolatilityTblRowTracker { get; set; }
    }
}
