//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Main_Table_ViewCellColumnHeading {
    
    /// <summary>
    /// cellcolumnheading control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlTableCell cellcolumnheading;
    
    /// <summary>
    /// ColumnPopUpMouseOverArea control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CommonControl_LiteralElement ColumnPopUpMouseOverArea;
    
    /// <summary>
    /// MyPlaceHolder control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.PlaceHolder MyPlaceHolder;
    
    /// <summary>
    /// ColumnPopUpMouseOverAreaClose control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CommonControl_LiteralElement ColumnPopUpMouseOverAreaClose;
    
    /// <summary>
    /// ColumnPopUpContent control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CommonControl_LiteralElement ColumnPopUpContent;
    
    /// <summary>
    /// ColumnPopUpLiteral control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Literal ColumnPopUpLiteral;
    
    /// <summary>
    /// ColumnPopUpContentClose control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CommonControl_LiteralElement ColumnPopUpContentClose;
}
