//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Main_Table_ViewCellRowHeading {
    
    /// <summary>
    /// FieldsDisplayDiv control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CommonControl_LiteralElement FieldsDisplayDiv;
    
    /// <summary>
    /// FieldsDisplayPlaceHolder control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.PlaceHolder FieldsDisplayPlaceHolder;
    
    /// <summary>
    /// FieldsDisplayDivClose control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CommonControl_LiteralElement FieldsDisplayDivClose;
    
    /// <summary>
    /// FieldsDisplayPopUp control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CommonControl_LiteralElement FieldsDisplayPopUp;
    
    /// <summary>
    /// PopUpFieldsDisplayPlaceHolder control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.PlaceHolder PopUpFieldsDisplayPlaceHolder;
    
    /// <summary>
    /// FieldsDisplayPopUpClose control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CommonControl_LiteralElement FieldsDisplayPopUpClose;
}
