// <auto-generated />
namespace ClassLibrary1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class July17at1pm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(July17at1pm));
        
        string IMigrationMetadata.Id
        {
            get { return "201407171655201_July17at1pm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
