//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.Admin {
    
    
    public partial class Guarantees {
        
        /// <summary>
        /// dollarValuePerPoint control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox dollarValuePerPoint;
        
        /// <summary>
        /// discountForGuarantees control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox discountForGuarantees;
        
        /// <summary>
        /// totalUnconditionalGuaranteesEarnedEver control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label totalUnconditionalGuaranteesEarnedEver;
        
        /// <summary>
        /// totalConditionalGuaranteesEarnedEver control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label totalConditionalGuaranteesEarnedEver;
        
        /// <summary>
        /// totalConditionalGuaranteesPending control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label totalConditionalGuaranteesPending;
        
        /// <summary>
        /// maximumTotalGuarantees control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox maximumTotalGuarantees;
        
        /// <summary>
        /// maximumGuaranteePaymentPerHour control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox maximumGuaranteePaymentPerHour;
        
        /// <summary>
        /// allowApplicationsWhenNoConditionalGuaranteesAvailable control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox allowApplicationsWhenNoConditionalGuaranteesAvailable;
        
        /// <summary>
        /// conditionalGuaranteesAvailableForNewUsers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox conditionalGuaranteesAvailableForNewUsers;
        
        /// <summary>
        /// conditionalGuaranteesAvailableForExistingUsers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox conditionalGuaranteesAvailableForExistingUsers;
        
        /// <summary>
        /// conditionalGuaranteeTimeBlockInHours control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox conditionalGuaranteeTimeBlockInHours;
        
        /// <summary>
        /// SetBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button SetBtn;
    }
}
